import type { ParserVariant, ThreadCapture } from "./types";
import type { ReviewSession } from "./lib/session";
import type {
  TiebaReadRequest,
  TiebaNestedPageProjection,
  TiebaNestedParseContext,
} from "./lib/tiebaApi";
import type { TiebaTransportResponse } from "./lib/tiebaTransport";

/**
 * The background constructs this from the active review session. It contains
 * only stable ids/selectors needed for navigation; reply text and usernames
 * never need to cross the jump-message boundary.
 */
export interface EvidenceLocator {
  replyId: string;
  siteReplyId: string | null;
  /** Public floor metadata used only to accelerate an in-page virtual-list scan. */
  floor: number | null;
  anchor: string;
  parentReplyId: string | null;
  parentSiteReplyId: string | null;
  parentAnchor: string | null;
  isNested: boolean;
  parserVariant: ParserVariant;
}

export type CaptureProgressPhase =
  | "validation"
  | "sync"
  | "main"
  | "nested"
  | "coverage";

export type CaptureProgressStatus =
  | "running"
  | "complete"
  | "cancelled"
  | "error";

/**
 * Body-free progress for one explicit whole-thread read. The request id is
 * generated by the caller when available, so a side panel can ignore delayed
 * events from an older run on the same tab.
 */
export interface CaptureProgressMessage {
  type: "CAPTURE_PROGRESS";
  tabId: number;
  requestId: string;
  phase: CaptureProgressPhase;
  completed: number;
  total: number;
  status: CaptureProgressStatus;
}

export interface TabReviewContext {
  tabId: number;
  url: string | null;
  threadId: string | null;
  session: ReviewSession | null;
  captureProgress: CaptureProgressMessage | null;
}

export interface ValidatedReviewSnapshot {
  valid: true;
  session: ReviewSession;
}

export type SidePanelRequest =
  | { type: "CAPTURE_WHOLE_THREAD"; tabId?: number; requestId?: string }
  | { type: "CANCEL_CAPTURE"; tabId: number; requestId?: string }
  | { type: "CAPTURE_ACTIVE_PAGE" }
  | { type: "GET_ACTIVE_SESSION" }
  | { type: "GET_TAB_REVIEW_CONTEXT"; tabId: number }
  | {
      type: "VALIDATE_REVIEW_SNAPSHOT";
      tabId: number;
      threadId: string;
      sessionUpdatedAt: string;
    }
  | { type: "GET_CLOUD_PERMISSION_STATUS" }
  | { type: "CLEAR_ACTIVE_SESSION" }
  | { type: "JUMP_TO_REPLY"; replyId: string };

export type ContentRequest =
  | { type: "PARSE_TIEBA_PAGE" }
  | { type: "GET_PAGE_URL" }
  | {
      type: "START_DYNAMIC_CAPTURE";
      threadId: string;
      documentInstanceId: string;
      allowMissingContainer: boolean;
    }
  | {
      type: "PARSE_TIEBA_NESTED_HTML";
      html: string;
      context: TiebaNestedParseContext;
    }
  | {
      type: "FETCH_TIEBA_READ_API";
      request: TiebaReadRequest;
    }
  | {
      type: "JUMP_TO_REPLY";
      locator: EvidenceLocator;
      /** Expected Tieba thread identity; content must reject another thread. */
      expectedThreadId: string;
    };

/** Body-free hint emitted after an explicitly reviewed SPA changes. */
export interface DynamicContentChangedMessage {
  type: "TIEBA_DYNAMIC_CONTENT_CHANGED";
  threadId: string;
  url: string;
  documentInstanceId: string;
  /** Random replay token; it is not derived from reply text or usernames. */
  signature: string;
}

/** Body-free warning that the reviewed SPA changed URL without a reload. */
export interface PageIdentityChangedMessage {
  type: "TIEBA_PAGE_IDENTITY_CHANGED";
  previousThreadId: string;
  currentUrl: string;
  documentInstanceId: string;
}

/** Messages accepted by the background from the side panel. */
export type ExtensionRequest = SidePanelRequest;

export type ExtensionErrorCode =
  | "TIEBA_PERMISSION_MISSING"
  | "RESTRICTED_PAGE"
  | "SCRIPT_INJECTION_FAILED"
  | "PAGE_NOT_READY"
  | "PAGE_LAYOUT_UNSUPPORTED"
  | "PAGE_PARSE_FAILED"
  | "TIEBA_READ_API_FAILED"
  | "TIEBA_READ_API_RESPONSE_INVALID"
  | "TIEBA_READ_API_RATE_LIMITED"
  | "CAPTURE_CANCELLED"
  | "EVIDENCE_NOT_LOADED"
  | "INVALID_TIEBA_PAGE"
  | "SESSION_STALE"
  | "CLOUD_PERMISSION_CLEANUP_FAILED"
  | "UNKNOWN";

export type ExtensionResponse<T = unknown> =
  | { ok: true; data: T }
  | { ok: false; error: string; code?: ExtensionErrorCode };

export interface SessionUpdatedMessage {
  type: "SESSION_UPDATED";
  session: ReviewSession;
}

export interface SessionClearedMessage {
  type: "SESSION_CLEARED";
  tabId: number;
  reason: "navigation" | "manual";
}

export interface SessionSuspendedMessage {
  type: "SESSION_SUSPENDED";
  tabId: number;
  reason: "url_unavailable";
}

export type CaptureResponse = ExtensionResponse<ReviewSession>;
export type SessionResponse = ExtensionResponse<ReviewSession | null>;
export type ParseResponse = ExtensionResponse<ThreadCapture>;
export type NestedParseResponse = ExtensionResponse<TiebaNestedPageProjection>;
export type TiebaReadResponse = ExtensionResponse<TiebaTransportResponse>;

export function isCaptureProgressMessage(
  value: unknown,
): value is CaptureProgressMessage {
  if (!value || typeof value !== "object") return false;
  const candidate = value as Partial<CaptureProgressMessage>;
  return (
    candidate.type === "CAPTURE_PROGRESS" &&
    typeof candidate.tabId === "number" &&
    Number.isInteger(candidate.tabId) &&
    candidate.tabId > 0 &&
    typeof candidate.requestId === "string" &&
    candidate.requestId.length > 0 &&
    candidate.requestId.length <= 128 &&
    (candidate.phase === "validation" ||
      candidate.phase === "sync" ||
      candidate.phase === "main" ||
      candidate.phase === "nested" ||
      candidate.phase === "coverage") &&
    typeof candidate.completed === "number" &&
    Number.isInteger(candidate.completed) &&
    candidate.completed >= 0 &&
    typeof candidate.total === "number" &&
    Number.isInteger(candidate.total) &&
    candidate.total >= 0 &&
    candidate.completed <= candidate.total &&
    (candidate.status === "running" ||
      candidate.status === "complete" ||
      candidate.status === "cancelled" ||
      candidate.status === "error")
  );
}

export function isSessionUpdatedMessage(
  value: unknown,
): value is SessionUpdatedMessage {
  return Boolean(
    value &&
      typeof value === "object" &&
      "type" in value &&
      value.type === "SESSION_UPDATED" &&
      "session" in value,
  );
}

export function isSessionClearedMessage(
  value: unknown,
): value is SessionClearedMessage {
  return Boolean(
    value &&
      typeof value === "object" &&
      "type" in value &&
      value.type === "SESSION_CLEARED" &&
      "tabId" in value &&
      typeof value.tabId === "number",
  );
}

export function isSessionSuspendedMessage(
  value: unknown,
): value is SessionSuspendedMessage {
  return Boolean(
    value &&
      typeof value === "object" &&
      "type" in value &&
      value.type === "SESSION_SUSPENDED" &&
      "tabId" in value &&
      typeof value.tabId === "number",
  );
}
